### ISSUE TITLE
County select word clipping

### ISSUE THREAD

**Issue by keyfer** [DesignRevision/shards-ui#1]
Firstly, this is beautiful. Great work. 

## Current Behavior
The bottom of the `g` is getting clipped:
![https://screenshot.click/08-29-u2hyc-z7jpp.jpg](https://screenshot.click/08-29-u2hyc-z7jpp.jpg)

## Possible Solution
On `.custom-select` the line height should be `1.2` instead of `1.1`.

![https://screenshot.click/08-30-8zhuf-njra8.jpg](https://screenshot.click/08-30-8zhuf-njra8.jpg)

**Comment by hisk** [comment]
Thank you @keyfer , I'm glad you like it! 😄
