### ISSUE TITLE
Layout issues for Shards demo in IE11

### ISSUE THREAD

**Issue by balabanov** [DesignRevision/shards-ui#11]
I've noticed that the [Shards demo](https://designrevision.com/demo/shards/extra/app-promo.html) has some rendering issues in IE11.

## Current Behavior

App image is vertically misaligned and the cards layout has some width issues.
![2017-12-06 13_50_18-shards - agency landing page built with shards - a modern ui toolkit](https://user-images.githubusercontent.com/921147/33660479-98535726-da8c-11e7-9a01-7bc377160dcf.png)

## Steps to Reproduce
1. Launch IE11 (11.1000.17025.0)
2. Open https://designrevision.com/demo/shards/extra/app-promo.html

## Context (Environment)

Windows 10, IE11 (11.1000.17025.0)

**Comment by hisk** [comment]
Thank you very much for taking the time to submit this issue @balabanov ! I'm on it. 😄

**Comment by hisk** [comment]
This issue was fixed in e1edfcc28351326cd4940eba2571d8d1b9e2b6d8.
