### ISSUE TITLE
Bootstrap 4 does not use input-group-addon

### ISSUE THREAD

**Issue by artknight** [DesignRevision/shards-ui#13]
Bootstrap 4 does not use `input-group-addon` any longer. 

It uses `input-group-prepend` and `input-group-append`. 

Please update your code base!

**Comment by artknight** [comment]
what's the progress on this?

**Comment by hisk** [comment]
@artknight Sorry for the huge delay. We are already working on updating Shards to work with Bootstrap 4 final. Expect updates soon. 😄

**Comment by tristanmarsh** [comment]
Great News!

**Comment by hisk** [comment]
This issue was fixed in e1edfcc28351326cd4940eba2571d8d1b9e2b6d8.

**Comment by Geczy** [comment]
You mean the monolith commit that took 9 days to load? lol

**Comment by hisk** [comment]
@Geczy I started the BS4 final upgrade in the initial private repo I created before releasing Shards publicly and then just dumped the whole thing here. I know, bad practice, but from now on everything will be done more incrementally and in the public repo. 😄

**Comment by alim-ansari** [comment]
use input-group-text
