### ISSUE TITLE
problem with checkbox when using it with angular 5

### ISSUE THREAD

**Issue by yiss** [DesignRevision/shards-ui#14]
The checkbox doesn't show properly when using it with Angular 5, any thoughts on what may cause the problem ?
Image : https://ibb.co/jPyK9G

**Comment by bogdanciuca** [comment]
Are you using a beta version of Bootstrap 4?

**Comment by hisk** [comment]
@yiss I haven't tested Shards with Angular 5 and I'm not aware of its internals or if they're compatible at all. Can you please tell me more about your current setup so I can try to reproduce this issue locally?

**Comment by dnkmiller** [comment]
I have the same issue after upgrading to Bootstrap V4 (rather than beta) so assume that is the issue?

**Comment by yiss** [comment]
`"dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "bootstrap": "4.0.0",
    "core-js": "^2.4.1",
    "jquery": "^3.3.1",
    "lt-themify-icons": "^1.1.0",
    "popper": "^1.0.1",
    "popper.js": "^1.12.9",
    "rxjs": "^5.5.6",
    "shards-ui": "^1.1.2",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "1.6.5",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.6.2"
  }`
@hisk Im using the version 4.0.0 of bootstrap, but I don't think it's an Angular problem, I think it's a bootstap issue somehow the checkbox is forced to have 2px width when inspecting the css

**Comment by hisk** [comment]
@dnkmiller @yiss Unfortunately Shards does not currently support the final version of Bootstrap 4, only beta-1. We are already working internally on updating it to the latest version. Expect updates soon. 😃

**Comment by yiss** [comment]
@hisk You're right the problem is a Bootstrap 4.0.0 problem, I don't have this problem using the version 4.0.0-beta.2, thank you :)
