### ISSUE TITLE
[Discussion] Vuejs Shards components

### ISSUE THREAD

**Issue by rodrigorhas** [DesignRevision/shards-ui#15]
Hey :). What about Vue.js instead of jQuery?
There are a lot of benefits around this "migration".
Did you think about it ?

- Modularization
- Scalability
- Vuejs support :D
- SFC (single file components)
- More maintainable code

Sorry if this isn't the best place to discussion

**Comment by Geczy** [comment]
Why not reactjs?

**Comment by rodrigorhas** [comment]
Because Vuejs is too easy to learn by the learning curve and its the easiest "lib / ecosystem / framework" at the moment. IMHO.

**Comment by hisk** [comment]
@rodrigorhas @Geczy Great proposals! 👍 I also thought about this for a while and I think it would be great to build both React and Vue versions of Shards. I snoozed the idea until Bootstrap 4 final was released to reduce the amount of potential overhead created by possible inconsistencies between versions.

However, I'm afraid we won't be able to fully take on both projects for now, but I am willing to create a plan and allow more members of the community to get involved and contribute.

**Comment by rodrigorhas** [comment]
Wow. So nice  @hisk. Thanks for reply.

**Comment by abr4xas** [comment]
@hisk check this: https://bootstrap-vue.js.org/ this can help to build a new version of shards with vue.

**Comment by dionfananie** [comment]
Please, it would be awesome when you build using vue :D !

**Comment by sebastienvercammen** [comment]
Adding my +1 for Vue.js.

**Comment by abr4xas** [comment]
@hisk what if you give us acces to a specific repo to work with vue / react?

**Comment by hisk** [comment]
Thanks for your support and patience so far everyone! 🙇

@abr4xas I don't think that would be necessary as both React and Vue versions are almost complete and scheduled to be released very soon (next month). I know this took a while and even though I found handling all the products on my own a bit challenging I reconsidered getting external help for the initial release.

**Comment by abr4xas** [comment]
@hisk no problem dude!!

**Comment by rodrigorhas** [comment]
I'll start some sketch at my own, just for practice and studies.
@hisk :)

**Comment by andreliem** [comment]
Actually, I've been considering building out Vue.js components with Shards as part of the vuejsradar.com articles I write... so glad I came across this thread here! Shards is awesome and I think it would compliment Vuejs really well.

**Comment by Lahori-Jawan** [comment]
okay. I am done with patience. @rodrigorhas  @andreliem I have already done integrating it with Vue [here](https://github.com/Lahori-Jawan/vshards) :)

**Comment by hisk** [comment]
@rodrigorhas @Lahori-Jawan 

I'm super excited to see how much demand has been around this and while I truly understand everyone, I'm making another step in asking you for a little bit more patience. 😁

Shards Vue is a few weeks closer to the launch and it will be released with at least 80%+ Bootstrap 4 compatibility (the remaining of which will be community-driven after the initial release), integrated documentation and many more awesome features. That's not only re-writing Bootstrap 4 as Vue components from scratch, but also adding Shards' extra functionality on top.

While I haven't talked much about this, DesignRevision is a one-man show and building projects worth using that is also meeting the quality standards I've been trying to meet so far, is taking time.

@andreliem That's really great to hear and I'm looking forward to see what you come up with. If you plan on building components that won't be available out of the box, I will definitely consider integrating them if you'd like. Keep up the great work with VueJS Radar. 👏

**Comment by hisk** [comment]
@rodrigorhas @Geczy @Lahori-Jawan @andreliem @abr4xas @sebastienvercammen @dionfananie 

**🎉Shards Vue is now [available on GitHub](https://github.com/designrevision/shards-vue) and as an [NPM package](https://www.npmjs.com/package/shards-vue).**

It covers more than 85% of all Bootstrap 4 components and also includes support for all the custom components that came with Shards.

All components are properly documented with minor features missing that will be obvious based on the component's props definition. I'm also working "as we speak" on deploying the documentation live and setting up the official product page.

Make sure to check it out, give it a spin and open a new issue in case you find anything.

Taking this project to a state that I am really happy with and comfortable to release took a while. However, I am really happy with the results so far and during the next couple of weeks, I will focus on updating and improving Shards while maintaining this project in order to get it to 100% Bootstrap 4 coverage.

**Thank you for your support and patience!** 🙇

**Comment by Geczy** [comment]
Congrats on the release. React in sight?

**Comment by hisk** [comment]
@Geczy The React version is a little bit rough on the edges, but I plan to release it in 3-4 weeks, after another round of updates (Bootstrap 4.1.3) and improvements for Shards, Shards Dashboard Pro and Shards Dashboard Lite. 😁

**Comment by andreliem** [comment]
Great work @hisk on the vue shards. I'm currently using shards for a new project and having a vue version will be super handy.

**Comment by robertsamarji** [comment]
Loving the Shards UI kit. Holding out for the React version, can't wait!

**Comment by blcarson** [comment]
Is it possible to get the sketch source for this like you've included with the vue pro version?

**Comment by hisk** [comment]
@blcarson Hey there! 👋 You can download the Sketch file [here](https://designrevision.com/downloads/shards/). 😄
