### ISSUE TITLE
How to enable navigation?

### ISSUE THREAD

**Issue by jinfagang** [DesignRevision/shards-ui#16]
I seek documentation and found not such describe which how to enable a navigationbar just like the **shards** official website?

**Comment by hisk** [comment]
@jinfagang Please make sure you check out the actual [extra demo page markup](https://github.com/DesignRevision/shards-ui/blob/master/src/extras/shards-demo.html) included in the package. Also, you can read more about how you can create navbars in the [official Bootstrap 4 documentation](https://getbootstrap.com/docs/4.0/components/navbar/). :)
