### ISSUE TITLE
Tabs component

### ISSUE THREAD

**Issue by wbhob** [DesignRevision/shards-ui#17]
I am wondering if there is a plan for an implementation of the Bootstrap Tabs component. I know this is for bugs, but there is nowhere to request a feature.

**Comment by hisk** [comment]
@wbhob Not sure I understand this request. The core Bootstrap 4 [tabs](https://getbootstrap.com/docs/4.0/components/navs/#tabs) are already adjusted to match Shards' design. You can also see an [example in the docs](https://designrevision.com/docs/shards/cards.html) showcasing tabs within cards. Please provide a link If you are referring to a 3rd party component library or something similar. 😄

**Comment by wbhob** [comment]
Oh, I see. I was thinking more of a tabs subnavigation, like the Ant Design component (but that's not an official bootstrap component, so I don't know why it would be here). Thanks!
