### ISSUE TITLE
Shards UI doesn't work as submodule

### ISSUE THREAD

**Issue by dlucian** [DesignRevision/shards-ui#18]
## Expected Behavior

Adding shards-ui as a submodule for a bigger project does not work as shards.scss imports a bootstrap 4 module via relative path. 

## Current Behavior

When using shards-ui as submodule via:

```
git submodule add https://github.com/DesignRevision/shards-ui.git
```

Building the application fails due to:

```
Module build failed:
@import "../../node_modules/bootstrap/scss/functions";
^
      File to import not found or unreadable: ../../node_modules/bootstrap/scss/functions.
Parent style sheet: /Users/lucian/...../shards-ui/src/scss/shards.scss
      in /Users/lucian/...../shards-ui/src/scss/shards.scss (line 9, column 1)
```

This happens because of the `@import` in https://github.com/DesignRevision/shards-ui/blob/master/src/scss/shards.scss#L9

## Possible Solution

Remove `../../` so that webpack finds node_modules/bootstrap, but this works *only if* webpack looks for includes at project root.

## Steps to Reproduce

- Create a new app that uses Webpack (for example a VueJS app)
- Add shards-ui as submodule
- `@import "./../../shards-ui/src/scss/shards.scss"` in the app's app.scss
- `npm run dev`

## Context (Environment)

MacOS High Sierra / Webpack 3.11.0

## Possible Implementation

Pending PR coming soon. The solution is not ideal but ideally won't break the standalone version and would also work via submodule.

**Comment by ben182** [comment]
When do u plan to release the patch?

**Comment by hisk** [comment]
@ben182 During this weekend or Monday at the latest with a couple of other small improvements. 😄

**Comment by skeemer** [comment]
I'm having problems with this when using the shards-ui package.
Changing to the following seems to work. Is this an npm version thing or ...?

`@import "~bootstrap/scss/functions";`

**Comment by psenechal** [comment]
That line should probably read

@import “~bootstrap/scss/functions”;

Use ~ instead of -

**Comment by hisk** [comment]
@skeemer @psenechal I apologize for the delay. Can you please clarify how you are compiling the SCSS files? 😄
