### ISSUE TITLE
Z-index issues at dashboard presentation site

### ISSUE THREAD

**Issue by rodrigorhas** [DesignRevision/shards-ui#30]
I'll give you more details about these issues

### Mobile only - hardware and software description
__Google Chrome__: 65.0.3325.109(Versão oficial) 32 bits
__Revision__: f412f53af6f3abcd6165b6cf0859dad2e88ff87d-refs/branch-heads/3325@{#626}
__SO__: Android 6.0.0; LG-K430 Build/MRA58K
__JavaScript__: V8 6.5.254.28
__User Agent__: Mozilla/5.0 (Linux; Android 6.0; LG-K430 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.109 Mobile Safari/537.36

## Main menu is under section content
![](https://i.imgur.com/EeQb0d1.png)

## Main menu is under `select` element
![](https://i.imgur.com/gvVZVKN.png)

## Button overflow
![](https://i.imgur.com/BRdR23u.png) 

## Weird behave caused by 2nd issue (select element)
![](https://i.imgur.com/o8Nn3Nj.png)

PS: english isn't my main language

**Comment by hisk** [comment]
@rodrigorhas Thank you so much for taking the time to submit this! 😄

**Comment by rodrigorhas** [comment]
You're welcome @hisk, i love this theme and ill contribute whenever is possible

**Comment by hisk** [comment]
I created a separate repo for the main site and moved this issue in there as it made more sense. :)

https://github.com/DesignRevision/designrevision.com/issues/1
