### ISSUE TITLE
noUiSlider v11.1.0 does not work with current CSS !!!

### ISSUE THREAD

**Issue by artknight** [DesignRevision/shards-ui#31]
I have upgraded our noUiSlider to the latest version ( 11.1.0 ) and shards-ui CSS breaks the slider. We are forced to resort to the native noUiSlider CSS. Please fix this.

Here is the screenshot of what happens

<img width="764" alt="screen shot 2018-04-04 at 4 22 45 pm" src="https://user-images.githubusercontent.com/157762/38332682-923edc02-3824-11e8-81fb-d8806163dfc3.png">

**Comment by artknight** [comment]
@hisk any idea when this might be released?

**Comment by hisk** [comment]
@artknight Expect the next patch (which includes the fix for this issue) to be released in the next few days, at the latest by Monday.

**Comment by hisk** [comment]
@artknight This issue was fixed in https://github.com/DesignRevision/shards-ui/pull/33

**Comment by artknight** [comment]
@hisk Thank you for the fix!!! I just double-checked and it indeed works!

I had to make one change though in _custom-slider.scss on line 17
`.noUi-handle {
      right: -10px; //changed from -17px
      left: auto;
    }`
...otherwise the handles were not aligned correctly.

**Comment by hisk** [comment]
@artknight You are right, It should be `-10px`. 😄 I'll push the fix for this in the upcoming update that will also add support for Bootstrap 4.1.1. Thanks!
