### ISSUE TITLE
Uncaught TypeError with Datepicker inside modal

### ISSUE THREAD

**Issue by papakay** [DesignRevision/shards-ui#35]
I want to really the great work you guys have done with this. It's incredible.

Please i'm having issue in getting the datepicker to work properly inside modal. The datepicker shows up but a jquery error is thrown which distort the modal size when i set modal-lg as the size of the modal.

<img width="533" alt="screen shot 2018-05-07 at 7 10 13 am" src="https://user-images.githubusercontent.com/5013738/39687411-433a57e2-51c6-11e8-9ce8-c641b5163ab0.png">

**Comment by hisk** [comment]
@papakay Thanks, I'm really glad that you like Shards! Can you please provide more details about your use case and maybe some code so I can try to recreate the issue locally?

**Comment by papakay** [comment]
Thanks immensely at @hisk.

I found out the issue is not from Shards but from bootstrap datepicker. 

There was a temporary hack given at https://github.com/uxsolutions/bootstrap-datepicker/issues/2370
