### ISSUE TITLE
How about a better license?

### ISSUE THREAD

**Issue by AdityaAnand1** [DesignRevision/shards-ui#4]
>  1.4. - Creation of "Software as a Service" (SaaS) application(s).
         (eg. generators, etc) - NO
  1.5. - Creation of product(s) aimed for specific platform(s).
         (eg. WordPress Themes, etc) - NO

...

Seriously?

**Comment by hisk** [comment]
@AdityaAnand1 I understand your frustration and the license is subject to change in the near future to a more permissive alternative.

**Comment by peterbrinck** [comment]
I have now seen multiple people mentioning the license.
And I really think, if you want this project to take off, that you need to change the license.

**Comment by hisk** [comment]
@peterbrinck I am aware and I find it interesting how summarising a license's terms can impact a product. There are many open source projects with similar strict license terms that took off without any complaints from the community.

The current license is quite permissive except for users that want to build and **commercially distribute end-products based on Shards** _(eg. static layouts or WordPress, Drupal, etc themes purposed for sale)_ or plan on building SaaS platforms or generators that use Shards as a resource _(also covering mostly profit-oriented businesses)_. 

To put it short, if you're not a business trying to profit from distributed products based on Shards, there's no reason to worry about.

**Comment by AdityaAnand1** [comment]
>products based on Shards

Uhmm, that is extremely vague and covers every single use case I can think of. Also there are other kinds of SaaS, not just "generators".

If you're simply trying to make $$ off this (which, by all means, you're entitled to), consider adding a revenue clause for businesses. That is, say if a company makes more than $100k annually or something and wants to use Shard in their product then they'll need to purchase a license, the price of which is at your discretion. Something like what [Unity](https://store.unity.com/products/unity-personal) and so many others are doing exactly to avoid having weirdly specific and oddly petty stuff in their licenses like "no SaaS" 😄 

Just my $0.02.

**Comment by hisk** [comment]
@AdityaAnand1 My goal is not to make money out of this and definitely not in the way you insinuate. The license is strict and it will remain so for now even if it hurts adoption. Everyone who wanted to integrate Shards into their SaaS project and couldn’t wait emailed me and asked for permission describing exactly what their service does, which I think is a considerate thing to do.

**Comment by georgemicheal21** [comment]
@hisk Which is it?

> license is subject to change in the near future to a more permissive alternative.

or 

>The license is strict and it will remain so for now even if it hurts adoption

I'm not going to tell you my website idea just to get permission and that's not considerate but rather presumptuous to think that most users would. If your goal is not to make money out of this then what possible logical reason is there to add those restrictions? To me this whole thing feels so much against the principles of open source. And from what I saw in the reddit and HN threads, this is indeed why most people are staying away from this repo.

By the way, as it stands right now, the license does not explicitly restrict someone from just copy pasting the source code and simply putting in a more permissive license. This is why people usually stick to the well known licenses like MIT, Apache or GPL which explicitly address all concerns.

**Comment by hisk** [comment]
@AdityaAnand1 @peterbrinck @georgemicheal21 I really hope a47e554 and [my latest announcement](https://designrevision.com/shards-relicensing-update-1-1-0/) will benefit the open source community and contribute to a better web without creating any more confusion. 😄

Now that this issue is closed for good, go and make something awesome with Shards! 🙌 I'd love to see what you come up and even give you some feedback.

**Comment by peterbrinck** [comment]
Amazing! :smile: 

Thanks a lot for changing the license!
I will now definitely go talk to my boss about a possible switch from our, now boring, material design to Shards! :smile:

**Comment by georgemicheal21** [comment]
@peterbrinck Just out of curiosity, what library/framework do you use right now? (for material design)

**Comment by peterbrinck** [comment]
@georgemicheal21 

We use Bootstrap and this: https://wrapbootstrap.com/theme/material-admin-responsive-admin-theme-WB011H985
