### ISSUE TITLE
Latest npm release is missing src folder

### ISSUE THREAD

**Issue by psenechal** [DesignRevision/shards-ui#48]
2.1.0 release included src/scss folder for shards. Current 2.1.1 release only has dist folder.

## Expected Behavior
2.1.1 release should include the src folder

## Current Behavior
2.1.1 release is missing the src folder

## Possible Solution
Publish the folder so that using shards dashboard can use the npm package for shards ui as in previous release.

## Steps to Reproduce
Update project to shards-ui 2.1.1. Attempt to build and an error is generated claiming that @import "~shards-ui/src/scss/shards"; cannot be found.

## Context (Environment)
Angular 7.2.6 project

**Comment by psenechal** [comment]
As a work-around for now, I downloaded the zip file of the project and copied the src folder into the shards-ui folder in node_modules

**Comment by hisk** [comment]
@psenechal My apologies! I have just fixed this in [2.1.2](https://www.npmjs.com/package/shards-ui/v/2.1.2). 😅
