### ISSUE TITLE
Checkbox issue

### ISSUE THREAD

**Issue by Bosskee** [DesignRevision/shards-ui#49]
Hey, I've encountered what might be a bug in the beautiful Shards!

I have a card where I want to use a few checkboxes, so I took the example code right from the documentation, but it ends up like this in my document:
[![Screenshot from Gyazo](https://gyazo.com/c155180ffe692bb73afbbc4112551b8f/raw)](https://gyazo.com/c155180ffe692bb73afbbc4112551b8f)
As you can see, the little checkmark appears next to the square where it's supposed to be. Is this a known issue? Any fix? :)

Code:
```
          <div class="card">
            <div class="card-header"> Options</div>
            <div class="card-body">
              <div class="custom-control custom-checkbox mb-3">
  <input type="checkbox" class="custom-control-input" id="customCheck1" checked>
  <label class="custom-control-label" for="customCheck1">Checkboxes are cool</label>
</div>

<!-- Normal Custom Checkbox -->
<div class="custom-control custom-checkbox mb-3">
  <input type="checkbox" class="custom-control-input" id="customCheck2">
  <label class="custom-control-label" for="customCheck2">Send me free pizza</label>
</div>

<!-- Disabled Custom Checkbox -->
<div class="custom-control custom-checkbox mb-3">
  <input type="checkbox" class="custom-control-input" id="customCheck3" disabled>
  <label class="custom-control-label" for="customCheck3">Oh no! I'm disabled!</label>
</div>
            </div>
          </div>
```

**Comment by Bosskee** [comment]
Didn't have latest version of Shards...!

**Comment by vstyler96** [comment]
I have the same issue, even with shards 3.0.0 and bootstrap 4. I am working with laravel. I can give more details if necesary
