### ISSUE TITLE
SCSS Compiling Error

### ISSUE THREAD

**Issue by skazhikadyadya** [DesignRevision/shards-ui#7]
Hi, thank you for nice framework.

When I try to compile .scss I see that:

```
cmd.exe /D /C call C:/Ruby24-x64/bin/scss.bat --no-cache --update shards.scss:shards.css
      error mixins/_box-shadow.scss (Line 3: () isn't a valid CSS value.)

Process finished with exit code 1
```

At _box-shadow.scss:
```
@mixin box-shadow($shadow...) {
  @if $enable-shadows {
    box-shadow: $shadow;
  }
}
```

How I can fix that? Thank you.

**Comment by hisk** [comment]
Thanks! I'm glad you like it. 😄

That is a little bit odd. Have you modified anything in Shards' SCSS files or tried to use the `box-shadow()` mixin without passing a value? Also, what SCSS compiler version are you using?

**Comment by skazhikadyadya** [comment]
No. I was only download sources as .zip and try to use phpstorm with default SCSS Watcher for compile new css (Poppins font unfortunately don't have cyrillic).

sass-3.5.1 in my Ruby install directory. 

Thanks.

**Comment by skazhikadyadya** [comment]
My bad, when I was change ruby to nodejs on phpstorm files watchers it's work well. Thank you. :)
