### ISSUE TITLE
Custom-toggle broken on Safari

### ISSUE THREAD

**Issue by iamDecode** [DesignRevision/shards-ui#8]
When using the custom-toggle class in Safari, the toggle knob animates out of bounds.

![screen recording 2017-12-01 at 01 04 pm](https://user-images.githubusercontent.com/1223300/33482321-bca50b8a-d698-11e7-9e13-12532c02b307.gif)

## Expected Behavior
The toggle knob animates left (off) to right (on).

## Current Behavior
On Safari the knob animates left out of the bounds of the control.

## Possible Solution
This problem is in the difference in parsing `left` in the following snippet:
```
.custom-toggle .custom-control-input:checked + .custom-control-indicator:after {
  left: calc(100% - 3px);
  -webkit-transform: translateX(-100%);
          transform: translateX(-100%);
}
```
Using  `left: 95%;` is a dirty way fix approximating the 3px margin, and seems to work in all browsers.

## Steps to Reproduce
1. Use Safari.
2. Click toggle.

## Context (Environment)
Tested on both Safari 10.0.2 (webkit 12604.4.7.1.3), and Safari Technology Preview 11.1 (release 44, webkit 12605.1.13.2). Ran on on MacOS Sierra 10.12.6.

**Comment by hisk** [comment]
This is great, thanks for your detailed submission! 😄 I'm on it!
